# Jaime Riley, tuh06971, TUID: 915402678
# 3207 Project 4: Signaling with multi-process and multi-threaded programs
# Lab Section 4

a.out: Riley_Project4_Process.c
	gcc -std=gnu99 -o a.out Riley_Project4_Process.c -Wall -Werror -lpthread -lm
